### ISSUE TITLE
Plugin only updates recent files when the plugin tab is open, otherwise it will never update.

### ISSUE THREAD

**Issue by lilskippyy** [tgrosinger/recent-files-obsidian#107]
Not sure if this is only happening to me. I search here and didn't find any issues open or closed.
The recent files list will only update if the plugin tab is open. If it is not open (visible or in context) the plugin will just not update the list. 

I'm quite sure it was not like that before. 
I'm on obsidian 1.7.6, installer v1.6.5

**Comment by Smitty010** [comment]
+1 here.  This is a serious bug since it's the whole point of the plugin

**Comment by zayKenyon** [comment]
I've tested this on versions 1.6.0 (24986b9fd61b7acaf9c56ca61cca785c2e0d481f), 1.7.0 (d6514cd41a610c76361513dda63a8d3d6a21437e), and 1.7.1 (0ec45cfe5eb90990cb1b67207feb5f6fae3d074d), they all produce the same results.

No version will maintain a list of recent files if there is no Recent Files pane loaded; though I found they do maintain the list when loaded but not visible.

I'm not sure if Recent Files can maintain this list if it is not loaded, since it wouldn't be active? Please let me know if I'm misinformed.

**Comment by zayKenyon** [comment]
Definitely weird that my plugin maintains a list when the plugin is invisible, which version of Obsidian are you using?

**Comment by tgrosinger** [comment]
This is might be caused by the new Deferred Views added in Obsidian 1.7.2 ([docs](https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views)). I haven't looked into this yes, but there should be a way that we can update the list internally even if the view isn't open.
