### ISSUE TITLE
Feature request: Ignore files or folders via glob pattern or regex rules

### ISSUE THREAD

**Issue by fanghuaqi** [tgrosinger/recent-files-obsidian#14]
Dear author,

    I found this great plugin to show recent files, it really helps. If possible, glob pattern or regex pattern ignore rules could be supported, it will be great.

Thanks
Huaqi

**Comment by luckman212** [comment]
@fanghuaqi Your request made me revisit my idea #5 and after some testing I've submitted PR #15 which I think addresses your needs.

Filename globs (`*`) are a shell concept. Regular Expressions translate better to TypeScript. 

You can achieve the same things, e.g. instead of `personal*` you could use `^personal.*`. Regex is actually more powerful than globs if you aren't familiar, you can do a lot more with it.

Example: you can match only files that start with numbers 3, 5 or 7 with `^[357].*`

@tgrosinger hope this is ok with you

**Comment by fanghuaqi** [comment]
Thanks @luckman212 , I will take a try

**Comment by luckman212** [comment]
Yes please let me know how it works for you.

In case you missed my comment in the other closed issue - here are instructions 

1. download [my fork](https://github.com/luckman212/recent-files-obsidian/archive/refs/heads/add-regex-matching.zip)
2. cd into the directory
3. build with `npm i && npm run build` 
4. copy over `main.js` to your `(vault)/.obsidian/plugins/recent-files-obsidian` dir.
5. restart Obsidian
6. adjust your Ignore list as needed

**Comment by fanghuaqi** [comment]
It works for me, I tried to ignore all the `README.md` in my subfolders, and add rules below:

~~~
# only this works
README
# this didn't work, with .md suffix
README.md
~~~

Thanks
Huaqi

**Comment by luckman212** [comment]
Yes I am stripping "`.md`" _if_ it occurs at the very end of the filename before testing for the regex match. I think because Obsidian hides the `.md` suffix almost everywhere, most users would expect this type of behavior.

I suppose I could add a toggle to turn off this behavior if you think it would be useful.

anyway, glad it's working for you!

**Comment by fanghuaqi** [comment]
Maybe no need to strip the suffix `.md`, so it could works for both cases. It really worked for me.

**Comment by luckman212** [comment]
I will make an update shortly.

**Comment by luckman212** [comment]
@fanghuaqi Please download the latest version and test. It does not strip the md extension anymore.

**Comment by fanghuaqi** [comment]
OK for `README.md` now.

**Comment by fanghuaqi** [comment]
Maybe author can directly merge this PR #15 , it works for my case.

**Comment by luckman212** [comment]
@fanghuaqi The changes were approved, we should see a new release soon

**Comment by tgrosinger** [comment]
Merged, I'll cut a release now.
