### ISSUE TITLE
Add Recent Button to iPad Navigation Pane

### ISSUE THREAD

**Issue by pixelinkmedia** [tgrosinger/recent-files-obsidian#35]
I noticed on the Desktop app of Obsidian, after installing Recent Files there is an icon on the top of the navigation pane next to the "Starred" button icon. This is quick and convenient.

However, on the iPad there is NO button on the navigation pane (only File Explorer, Folder, Sort). The only way to access the Recent Files is I have to drill backwards on the navigation where is says "File Explorer", then I will see the Recent File icon.

Can you add an icon button next to the "Sort" button on the navigation pane for quick access?

Thanks

**Comment by tgrosinger** [comment]
Hello,
Unfortunately I am not able to add a button there because that would require modifying the File Explorer core plugin which is not open source. I appreciate the suggestion though. Alternatively, you can open it from the Command Palette, which is often bound to swiping down from the top of the screen on mobile.

**Comment by pixelinkmedia** [comment]
That's too bad.

**Comment by uwe999** [comment]
I've posted this UI improvement suggestion:
https://forum.obsidian.md/t/feature-improve-general-ui-and-ux-in-ios-app/28648/2
maybe you can +1 it
