### ISSUE TITLE
How is Recent Files different that a simple dataview query?

### ISSUE THREAD

**Issue by PKeyes505** [tgrosinger/recent-files-obsidian#54]
How is Recent Files different that a simple dataview query? Example below will update a note dynamically which you can just pin.
```dataview
TABLE file.ctime as "Creation Date"
FROM ""
WHERE file.ctime > date(today) - dur(2 days) AND contains(tags, "#example-tag")
SORT file.ctime DESC
```

**Comment by cvh-obsi** [comment]
I think it makes the diff between last modified note (file.ctime) and last opened note.
ex: I have note A containing a link to note B. I haven't opened note A for very long time.
When I rename note B in note C, the link in note A will be updated and by this file.ctime will be updated.
With this plugin note A is not going up in the recent file list
I was using a query dataview but when I was renaming files, the last modified list received the many notes that were updated due to the renaming
