### ISSUE TITLE
Disambiguate long file names

### ISSUE THREAD

**Issue by magi44ken** [tgrosinger/recent-files-obsidian#59]
Problem: Note title that is longer than the pane width can't see the full title. If you have notes with similar long names, you can't distinguish them unless you open the note first.

Example:
Vegatable Soup Broccoli, Sweet, Spicy Recipe
Vegatable Soup Broccoli, Sweet Lemon Recipe

If it only display upto "Vegatable Soup Broccoli, S", you can tell which file from here.

Vegatable Soup Broccoli, S
Vegatable Soup Broccoli, S

Solution: Show the full note title in multiple lines.

**Comment by tgrosinger** [comment]
Thanks for the issue report. I agree that can be annoying.

I'm actually just using the same styling as the default file browser in Obsidian. I don't want to differ from how the file names are displayed there because it would risk becoming visually inconsistent.

The default file browser does however have a tooltip which pops up when you hover over a file and it shows the full file name. I think that could be a good solution for this issue.

**Comment by WilliamStone** [comment]
I have a similar issue that annoys me regarding files with same name but different path. e.g.
```
/Work/Develop/ProjectA/Design.md
/Work/Develop/ProjectB/Design.md
```
In Recent Files view, both files are shown as "Design", thus making them indistinguishable.
Currently what I can do is press Ctrl and hover mouse on file name to peek its content, but that's also annoying.

IMO there are a few options addressing this issue:
1. When mouse is hovering on file, popup a floating text showing the file's full path. 
    I prefer this option. Files opened recently with same name are minor percentage, so in most cases file name is enough to distinguish. Only in lesser cases one need to hover mouse on files to check its path.
3. Show path directly after file name, with gray color. 
    This is not so useful, because files with same name tend to be under the same branch of directory tree, making former part of path identical. Unless we reverse path level when displaying, but that looks weird.
